//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shap.StaticResources", typeof(StaticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\ba\.
        /// </summary>
        internal static string baPath {
            get {
                return ResourceManager.GetString("baPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\uts\config\.
        /// </summary>
        internal static string classDetailsPath {
            get {
                return ResourceManager.GetString("classDetailsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\uts\icon\.
        /// </summary>
        internal static string classIconPath {
            get {
                return ResourceManager.GetString("classIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\uts\img\.
        /// </summary>
        internal static string classImgPath {
            get {
                return ResourceManager.GetString("classImgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fam.
        /// </summary>
        internal static string FileNameFamily {
            get {
                return ResourceManager.GetString("FileNameFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ona.
        /// </summary>
        internal static string FileNameOldNumbersAvailable {
            get {
                return ResourceManager.GetString("FileNameOldNumbersAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to optr.
        /// </summary>
        internal static string FileNameOperator {
            get {
                return ResourceManager.GetString("FileNameOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regions.
        /// </summary>
        internal static string FileNameRegions {
            get {
                return ResourceManager.GetString("FileNameRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\uts\idvl\.
        /// </summary>
        internal static string idvlDetailsPath {
            get {
                return ResourceManager.GetString("idvlDetailsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\img\.
        /// </summary>
        internal static string imgPath {
            get {
                return ResourceManager.GetString("imgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\loc\idvl\.
        /// </summary>
        internal static string locIdvlPath {
            get {
                return ResourceManager.GetString("locIdvlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\loc\img\.
        /// </summary>
        internal static string locImgPath {
            get {
                return ResourceManager.GetString("locImgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\loc\.
        /// </summary>
        internal static string locPath {
            get {
                return ResourceManager.GetString("locPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log\.
        /// </summary>
        internal static string logPath {
            get {
                return ResourceManager.GetString("logPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\Milage\.
        /// </summary>
        internal static string mileagePath {
            get {
                return ResourceManager.GetString("mileagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\msc\.
        /// </summary>
        internal static string miscellaneousPath {
            get {
                return ResourceManager.GetString("miscellaneousPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data\report\.
        /// </summary>
        internal static string reportPath {
            get {
                return ResourceManager.GetString("reportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v3.2.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
